# Generated by Django 4.2.5 on 2023-09-12 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orcamentos', '0003_alter_orcamento_validade'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrPix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(upload_to='qrcode/% Y/% m/% d/', verbose_name='QRcode')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamentos.orcamento', verbose_name='Orçamento')),
            ],
        ),
    ]
