# Generated by Django 4.2.5 on 2023-09-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrpix',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode/% Y/% m/% d/', verbose_name='QRcode'),
        ),
    ]
