# Generated by Django 4.2.5 on 2023-09-12 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0003_alter_orcamento_validade'),
        ('pix', '0002_alter_qrpix_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrpix',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_pix', to='orcamentos.orcamento', verbose_name='Orçamento'),
        ),
    ]
