# Generated by Django 4.1 on 2023-01-09 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-created'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='telefonecontato',
            options={'ordering': ['-created'], 'verbose_name': 'Telefone', 'verbose_name_plural': 'Telefones'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(max_length=50, unique=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='telefonecontato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_telefone', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='telefonecontato',
            name='numero',
            field=models.CharField(max_length=20, unique=True, verbose_name='Telefone'),
        ),
    ]
