# Generated by Django 4.1 on 2023-01-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_alter_telefonecontato_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='CPF/CNPJ'),
        ),
    ]
