# Generated by Django 4.1 on 2023-01-25 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeMaoDeObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Mão de Obra',
                'verbose_name_plural': 'Tipos de Mãoes de Obras',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='MaoDeObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('preco_compra', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Preço Mão de Obra')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('tipo_de_mao_de_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_mao_obra', to='servicos.tipodemaodeobra', verbose_name='Tipo de mão de obra')),
            ],
            options={
                'verbose_name': 'Mão de obra',
                'verbose_name_plural': 'Mãos de Obras',
                'ordering': ['-created'],
            },
        ),
    ]
