# Generated by Django 4.2.1 on 2023-05-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaservico",
            name="nome",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nome"),
        ),
    ]
