# Generated by Django 4.1 on 2023-01-22 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0004_itemmaodeobra_alter_orcamento_codigo_and_more'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaoDeObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Mão de obra',
                'verbose_name_plural': 'Mãos de Obras',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TipoDeMaoDeObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Mão de Obra',
                'verbose_name_plural': 'Tipos de Mãoes de Obras',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
        migrations.DeleteModel(
            name='TipoDeServico',
        ),
        migrations.AddField(
            model_name='maodeobra',
            name='tipo_de_mao_de_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_mao_obra', to='servicos.tipodemaodeobra', verbose_name='Tipo de mão de obra'),
        ),
    ]
