# Generated by Django 4.1 on 2023-01-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_maodeobra_tipodemaodeobra_delete_servico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maodeobra',
            name='preco_mao_de_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Preço Mão de Obra'),
        ),
    ]
