# Generated by Django 4.1 on 2023-01-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_maodeobra_preco_mao_de_obra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maodeobra',
            old_name='preco_mao_de_obra',
            new_name='preco_compra',
        ),
    ]
