# Generated by Django 4.2.1 on 2023-05-07 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orcamentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Desconto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "porcetagem_desconto",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Por"
                    ),
                ),
            ],
            options={
                "verbose_name": "Desconto",
                "verbose_name_plural": "Descontos",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Proposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Proposta Numero"
                    ),
                ),
                (
                    "desconto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=8,
                        null=True,
                        verbose_name="Por",
                    ),
                ),
                (
                    "validade",
                    models.DateField(blank=True, null=True, verbose_name="Validade"),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposta_orcamento",
                        to="orcamentos.orcamento",
                        verbose_name="Proposta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposta",
                "verbose_name_plural": "Propostas",
                "ordering": ["-created"],
            },
        ),
    ]
