# Generated by Django 4.2.5 on 2023-09-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Desconto',
        ),
        migrations.RenameField(
            model_name='proposta',
            old_name='desconto',
            new_name='desconto_porcentagem',
        ),
        migrations.AddField(
            model_name='proposta',
            name='desconto_real',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8, null=True, verbose_name='Por'),
        ),
    ]
