# Generated by Django 4.2.5 on 2023-09-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0002_delete_desconto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='desconto_porcentagem',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8, null=True, verbose_name='Porcentagem'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='desconto_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Por'),
        ),
    ]
