# Generated by Django 4.2.5 on 2023-09-27 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0011_alter_orcamento_validade'),
        ('propostas', '0003_proposta_total_alter_proposta_desconto_porcentagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='orcamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposta_orcamento', to='orcamentos.orcamento', verbose_name='Proposta'),
        ),
    ]
