# Generated by Django 4.2.5 on 2023-09-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0004_alter_proposta_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='valor_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor da Entrada'),
        ),
    ]
