# Generated by Django 4.2.5 on 2023-09-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0005_proposta_valor_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
    ]
