# Generated by Django 4.2.5 on 2023-09-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0006_proposta_finalizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='nome',
        ),
        migrations.AlterField(
            model_name='proposta',
            name='codigo',
            field=models.CharField(max_length=30, unique=True, verbose_name='Codigo'),
        ),
    ]
