# Generated by Django 4.2.5 on 2023-10-01 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0012_alter_orcamento_validade'),
        ('propostas', '0007_remove_proposta_nome_alter_proposta_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='orcamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposta_orcamento', to='orcamentos.orcamento', verbose_name='Orcamento'),
        ),
    ]
