# Generated by Django 4.2.5 on 2023-10-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0008_alter_proposta_orcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='desconto_real',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Desconto'),
        ),
    ]
