# Generated by Django 4.2.5 on 2023-10-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0009_alter_proposta_desconto_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode/%Y/%m/%d', verbose_name='QRcode'),
        ),
    ]
