# Generated by Django 4.1 on 2023-01-12 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_alter_cliente_documento'),
        ('produtos', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='2023-01-jK1bX', editable=False, max_length=20, unique=True, verbose_name='Codigo')),
                ('total_produto', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Preço')),
                ('total_servico', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Preço')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Preço')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento_cliente', to='clientes.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico_orcamento', to='orcamentos.orcamento', verbose_name='Orçamento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_servico', to='servicos.servico', verbose_name='Serviço')),
            ],
        ),
        migrations.CreateModel(
            name='ItemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_orcamento', to='orcamentos.orcamento', verbose_name='Orcamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_produto', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item Produto',
                'verbose_name_plural': 'itens Produtos',
                'ordering': ['-created'],
            },
        ),
    ]
