# Generated by Django 4.2.1 on 2023-05-07 13:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0002_cliente_email"),
        ("empresas", "0001_initial"),
        ("produtos", "0001_initial"),
        ("servicos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "validade",
                    models.DateField(
                        default=datetime.date(2023, 5, 22), verbose_name="Validade"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Não Enviado"),
                            (1, "Em Analise"),
                            (2, "Aprovado"),
                            (3, "Cancelada"),
                        ],
                        default=0,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Codigo",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orcamento_cliente",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empresa_orcamento",
                        to="empresas.empresa",
                        verbose_name="Empresa para o Orçamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Preço"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Total",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produto_orcamento",
                        to="orcamentos.orcamento",
                        verbose_name="Orcamento",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_produto",
                        to="produtos.produto",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Produto",
                "verbose_name_plural": "itens Produtos",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ItemMaoDeObra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execurcao_parceiro",
                    models.BooleanField(
                        default=False, verbose_name="Execultado Por Parceiro"
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Preço"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Total",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
                ),
                (
                    "mao_de_obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_servico",
                        to="servicos.servico",
                        verbose_name="Serviço",
                    ),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mao_obra_orcamento",
                        to="orcamentos.orcamento",
                        verbose_name="Orçamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Servico",
                "verbose_name_plural": "Itens Serviços",
                "ordering": ["-created"],
            },
        ),
    ]
