# Generated by Django 4.1 on 2023-01-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='codigo',
            field=models.CharField(default='2023-01-5Fk8C', editable=False, max_length=20, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='total_produto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Total Produto'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='total_servico',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Total Serviço'),
        ),
    ]
