# Generated by Django 4.1 on 2023-01-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='codigo',
            field=models.CharField(default='2023-01-KRtpt', editable=False, max_length=20, unique=True, verbose_name='Codigo'),
        ),
    ]
