# Generated by Django 4.1 on 2023-01-26 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_alter_orcamento_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='codigo',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='validade',
            field=models.DateField(default=datetime.date(2023, 2, 10), verbose_name='Validade'),
        ),
    ]
