# Generated by Django 4.2.5 on 2023-09-12 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_alter_orcamento_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='validade',
            field=models.DateField(default=datetime.date(2023, 9, 27), verbose_name='Validade'),
        ),
    ]
