# Generated by Django 4.1 on 2023-01-20 12:06

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_alter_orcamento_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamento',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado em'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='codigo',
            field=models.CharField(default='2023-01-bnQ6p', editable=False, max_length=20, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='validade',
            field=models.DateField(default=datetime.date(2023, 2, 6), verbose_name='Validade'),
        ),
    ]
