# Generated by Django 4.1 on 2023-01-27 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0003_alter_orcamento_codigo_alter_orcamento_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='validade',
            field=models.DateField(default=datetime.date(2023, 2, 13), verbose_name='Validade'),
        ),
    ]
