# Generated by Django 4.1 on 2023-01-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0003_orcamento_created_orcamento_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaoDeObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Item mão de obra',
                'verbose_name_plural': 'Itens Mãos de Obras',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='codigo',
            field=models.CharField(default='2023-01-iEYvf', editable=False, max_length=20, unique=True, verbose_name='Codigo'),
        ),
        migrations.DeleteModel(
            name='ItemServico',
        ),
    ]
