# Generated by Django 4.1 on 2023-01-22 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_maodeobra_tipodemaodeobra_delete_servico_and_more'),
        ('orcamentos', '0004_itemmaodeobra_alter_orcamento_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaodeobra',
            name='mao_de_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_mao_obra', to='servicos.maodeobra', verbose_name='Mão de Obra'),
        ),
        migrations.AddField(
            model_name='itemmaodeobra',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mao_obra_orcamento', to='orcamentos.orcamento', verbose_name='Orçamento'),
        ),
    ]
