# Generated by Django 4.2.1 on 2023-05-04 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0004_itemmaodeobra_execurcao_parceiro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orcamento",
            name="validade",
            field=models.DateField(
                default=datetime.date(2023, 5, 19), verbose_name="Validade"
            ),
        ),
    ]
