# Generated by Django 4.1 on 2023-02-13 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0004_itemmaodeobra_execurcao_parceiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaodeobra',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='validade',
            field=models.DateField(default=datetime.date(2023, 2, 28), verbose_name='Validade'),
        ),
    ]
