# Generated by Django 4.2.5 on 2023-09-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0005_orcamento_total_equipamentos_orcamento_total_lucro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmaodeobra',
            options={'ordering': ['-created'], 'verbose_name': 'Item Mão de Obra', 'verbose_name_plural': 'Itens Maões de Obras'},
        ),
        migrations.RenameField(
            model_name='itemmaodeobra',
            old_name='preco',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='itemmaodeobra',
            name='execurcao_parceiro',
        ),
        migrations.RemoveField(
            model_name='itemmaodeobra',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='itemmaodeobra',
            name='total',
        ),
    ]
