# Generated by Django 4.1 on 2023-01-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0005_itemmaodeobra_mao_de_obra_itemmaodeobra_orcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='codigo',
            field=models.CharField(default='2023-01-TZRgB', editable=False, max_length=20, unique=True, verbose_name='Codigo'),
        ),
    ]
