# Generated by Django 4.2.1 on 2023-05-05 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamentos", "0005_alter_orcamento_validade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orcamento",
            name="validade",
            field=models.DateField(
                default=datetime.date(2023, 5, 22), verbose_name="Validade"
            ),
        ),
    ]
