# Generated by Django 4.1 on 2023-01-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0007_alter_orcamento_codigo_alter_orcamento_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaodeobra',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='codigo',
            field=models.CharField(default='2023-01-QkRkW', editable=False, max_length=20, unique=True, verbose_name='Codigo'),
        ),
    ]
