# Generated by Django 4.2.5 on 2023-09-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0007_remove_itemproduto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaodeobra',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
