# Generated by Django 4.1 on 2023-01-24 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0008_itemmaodeobra_total_alter_orcamento_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmaodeobra',
            old_name='mao_de_obra',
            new_name='preco_compra',
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='codigo',
            field=models.CharField(default='2023-01-bsuro', editable=False, max_length=20, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='validade',
            field=models.DateField(default=datetime.date(2023, 2, 8), verbose_name='Validade'),
        ),
    ]
