# Generated by Django 4.1 on 2023-01-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0009_rename_mao_de_obra_itemmaodeobra_preco_compra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmaodeobra',
            old_name='preco_compra',
            new_name='mao_de_obra',
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='codigo',
            field=models.CharField(default='2023-01-MAXWY', editable=False, max_length=20, unique=True, verbose_name='Codigo'),
        ),
    ]
