# Generated by Django 4.2.5 on 2023-09-26 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0009_itemproduto_preco_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemproduto',
            name='preco_unitario',
        ),
        migrations.AddField(
            model_name='itemproduto',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='itemproduto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='validade',
            field=models.DateField(default=datetime.date(2023, 10, 11), verbose_name='Validade'),
        ),
    ]
