# Generated by Django 4.2.5 on 2023-09-27 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0010_remove_itemproduto_preco_unitario_itemproduto_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='validade',
            field=models.DateField(default=datetime.date(2023, 10, 12), verbose_name='Validade'),
        ),
    ]
