# Generated by Django 4.1 on 2023-01-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0010_rename_preco_compra_itemmaodeobra_mao_de_obra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='codigo',
            field=models.CharField(default='2023-01-Nb13e', editable=False, max_length=20, unique=True, verbose_name='Codigo'),
        ),
    ]
