# Generated by Django 4.2.5 on 2023-10-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0013_alter_orcamento_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaodeobra',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='itemmaodeobra',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total'),
        ),
    ]
